title: "陈拾遗 Shiyi Eleven Chen"
author: "陈拾遗 Shiyi Eleven Chen"
description: "Code, create, conquer"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  #  - {title: "CV", url: "/pdfs/Resume_Eleven.pdf", icon: home}
  - {title: "Course projects", url: "/projectpage"}
  - {title: "Posts", file: "blog.md"}
  - {title: "gallery", url: "/gallery"}


external:                  # see http://fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/Eleven7825"}
  - {title: Linkedin, url: "https://www.linkedin.com/in/eleven-chen-388250196/"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
